baseurl = "/"
relativeurls = true
languageCode = "en-us"
title = "Quixotic Quant"
googleAnalytics = ""
disqusShortname = "42-design-work"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]


sectionPagesMenu = "main"

