baseurl = "/"
relativeurls = true
languageCode = "en-us"
title = "Quixotic Quant"
googleAnalytics = ""
disqusShortname = "quixoticquant.disqus.com"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]


sectionPagesMenu = "main"

